package AWS::Zocalo::Content::Folder;

use v5.010;
use strict;
use warnings;
use Method::Signatures;
use Scalar::Util::Reftype;
use Carp 'croak';
use AWS::Zocalo::User;
use Moo;
use namespace::clean

extends 'AWS::Zocalo::Content';

# ABSTRACT: A Zocalo Folder Object
 
# VERSION: Generated by DZP::OurPkg:Version
  
=head1 SYNOPSIS 

  use AWS::Zocalo::Content::Folder;

  $folder = AWS::Zocalo::Content::Folder->new( Id => 'fjkldsajfdsa' );

=head1 DESCRIPTION

Extends L<AWS::Zocalo::Content>, see that for all documentation.

=cut

1;
