package AWS::Zocalo::Content::Folder;

use v5.010;
use strict;
use warnings;
use Moo;
use Method::Signatures;
use Scalar::Util::Reftype;

extends 'AWS::Zocalo::Content';

# ABSTRACT: A Zocalo Folder Object
 
# VERSION: Generated by DZP::OurPkg:Version
  
=head1 SYNOPSIS 

  use AWS::Zocalo::Content::Folder;

  my $folder = AWS::Zocalo::Content::Folder->new( Id => 'fjkldsajfdsa' );

=head1 DESCRIPTION

Extends L<AWS::Zocalo::Content>, see that for all documentation.

=cut

method user_share(:$users,:$access = "VIEW") {
  $access = uc($access);
  if (! $access =~ /VIEW|CONTRIBUTE/) {
    croak("$access not valid, only VIEW|CONTRIBUTE are valid types");
  }

  my $body;
  if ( reftype( \@{$users} )->array ) {
    foreach my $user ( @{$users} ) {
      $body->{UserPermissionMap}{$user} = "$access";
    }
  } else {
    $body->{UserPermissionMap}{$users} = "$access";
  }
  
  $self->auth->api_post("/$self->{_type}/$self->{Id}/share", $body);
  $self->retrieve;
}

1;
