package AWS::WorkDocs::Content::Document;

use v5.010;
use strict;
use warnings;
use Moo;
use Method::Signatures;
use Scalar::Util::Reftype;

extends 'AWS::WorkDocs::Content';

# ABSTRACT: A WorkDocs Folder Object
 
# VERSION: Generated by DZP::OurPkg:Version
  
=head1 SYNOPSIS 

  use AWS::WorkDocs::Content::Document;

  my $Document = AWS::WorkDocs::Content::Document->new( Id => 'fjkldsajfdsa' );

=head1 DESCRIPTION

Extends L<AWS::WorkDocs::Content>, see that for all documentation.

=cut

1;
