package AWS::WorkDocs::Content::Folder;

use v5.010;
use strict;
use warnings;
use Method::Signatures;
use Scalar::Util::Reftype;
use Carp 'croak';
use AWS::WorkDocs::User;
use Moo;
use namespace::clean

extends 'AWS::WorkDocs::Content';

# ABSTRACT: A WorkDocs Folder Object
 
# VERSION: Generated by DZP::OurPkg:Version
  
=head1 SYNOPSIS 

  use AWS::WorkDocs::Content::Folder;

  $folder = AWS::WorkDocs::Content::Folder->new( Id => 'fjkldsajfdsa' );

=head1 DESCRIPTION

Extends L<AWS::WorkDocs::Content>, see that for all documentation.

=cut

1;
